steps:

  - id: 'Build container'
    name: 'gcr.io/cloud-builders/gcloud:latest'
    entrypoint: /bin/bash
    args:
      - '-c'
      - |
        gcloud beta builds submit --pack image=gcr.io/$PROJECT_ID/$_JOB:$_VERSION
  - id: 'Deploy to Cloud Run'
    name: 'gcr.io/cloud-builders/gcloud:latest'
    entrypoint: /bin/bash
    args:
      - '-c'
      - |
        ./test/retry.sh ""
substitutions:
  _JOB: logger
  _VERSION: manual